export const mesesDoAno = [
  "Janeiro",
  "Fevereiro",
  "Março",
  "Abril",
  "Maio",
  "Junho",
  "Julho",
  "Agosto",
  "Setembro",
  "Outubro",
  "Novembro",
  "Dezembro",
];

export const damymonths = [
  {
    resident_name: "Caué",
    months: [
      "n/s",
      true,
      true,
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ],
  },
  {
    resident_name: "Estefanio",
    months: [
      true,
      false,
      false,
      false,
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ],
  },
  {
    resident_name: "Felipe",
    months: [
      true,
      true,
      true,
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ],
  },
  {
    resident_name: "Gabriel Baez",
    months: [
      true,
      true,
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ],
  },
  {
    resident_name: "Gabriel Helyone",
    months: [
      "n/s",
      true,
      true,
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ],
  },
  {
    resident_name: "Gustavo",
    months: [
      true,
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ],
  },
  {
    resident_name: "Jonathan",
    months: [
      true,
      true,
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ],
  },
  {
    resident_name: "Mairon",
    months: [
      true,
      true,
      true,
      true,
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ],
  },
  {
    resident_name: "Mani",
    months: [
      true,
      true,
      true,
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ],
  },
  {
    resident_name: "Petrus",
    months: [
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ],
  },
  {
    resident_name: "Rennan",
    months: [
      true,
      true,
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ],
  },
  {
    resident_name: "Robson",
    months: [
      true,
      true,
      true,
      true,
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ],
  },
  {
    resident_name: "Thiago",
    months: [
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ],
  },
  {
    resident_name: "Zico",
    months: [
      true,
      true,
      true,
      true,
      true,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
    ],
  },
];

export const damyfines = [
  {
    resident_name: "Estefanio",
    desc: "Não lavou panos ",
    date: " 18/02/2024 ",
    status: false,
  },
  {
    resident_name: "Estefanio",
    desc: " Não lavou banheiro ",
    date: " 12/02/2024 ",
    status: false,
  },
  {
    resident_name: "Mani",
    desc: "Não lavou panos ",
    date: " 18/02/2024 ",
    status: false,
  },
  {
    resident_name: "Zico",
    desc: "Não fez a munutenção durante a sua semana ",
    date: " 18/11/2023 ",
    status: false,
  },
];

export const damypurchase = [
  {
    desc: "filtro de papel e papel higienico",
    author: "Manito",
    value: 44.56,
    link: "https://drive.google.com/file/d/1B8XmZbKL_8Rqy02v6kPwJ4Nn1_4UnHRA/view?usp=drive_link",
    date: "4/5/2024",
  },
  {
    desc: "Internet",
    author: "Manito",
    value: 148.97,
    link: "https://drive.google.com/file/d/1vaY7yzIYDze_dd6fB4pClBldmdik6fjK/view?usp=drive_link",
    date: "8/5/2024",
  },
  {
    desc: "compra parcial",
    author: "Manito",
    value: 14.37,
    link: "https://drive.google.com/file/d/1DjGQZzbwcX5gVXtWsvkvrzNweQTeBh5F/view?usp=sharing",
    date: "13/5/2024",
  },
  {
    desc: "compra geral",
    author: "Manito e Estefanio",
    value: 160.82,
    link: "https://drive.google.com/file/d/1DeKFbcDHm-NEJNci4aooEHH8jfgzom0P/view?usp=sharing",
    date: "13/5/2024",
  },
];

export const damyresume = {
  initialBalance: 1014.08,
  totalUsed: 368.72,
  currentBalance: 645.36,
  currentMonth: "Maio",
};
